export const classNames = {
  surface: {
    stage: 'surface-stage',
    window: 'surface-window',
    windowHeader: 'surface-window-header',
    windowBody: 'surface-window-body',
    windowFooter: 'surface-window-footer',
    windowBrand: 'surface-window-brand',
    windowIcon: 'surface-window-icon',
    windowIconGlyph: 'surface-window-icon-glyph',
    windowHeaderAction: 'surface-window-header-action',
    windowExit: 'surface-window-exit',
    windowExitTrigger: 'surface-window-exit-trigger',
    exitPopover: 'surface-exit-popover',
    exitPopoverTitle: 'surface-exit-popover-title',
    exitPopoverActions: 'surface-exit-popover-actions',
    windowTitle: 'surface-window-title',
    windowSubtitle: 'surface-window-subtitle',
    headingCopy: 'surface-heading-copy',
    pillRow: 'surface-pill-row',
    actionRow: 'surface-action-row',
    actionRowCompact: 'compact',
    previewGrid: 'surface-preview-grid',
    statusStrip: 'surface-status-strip',
    summaryStrip: 'surface-summary-strip',
    summaryText: 'surface-summary-text',
    linkedCard: 'surface-linked-card',
    linkedThumb: 'surface-linked-thumb',
    linkedCopy: 'surface-linked-copy'
  },
  resource: {
    modalStack: 'resource-modal-stack',
    modalSection: 'resource-modal-section',
    modalSectionTitle: 'resource-modal-section-title',
    modalSectionHead: 'resource-modal-section-head'
  },
  runtime: {
    list: 'runtime-list',
    item: 'runtime-item',
    itemHead: 'runtime-item-head',
    indexButton: 'runtime-index-button',
    summary: 'runtime-summary',
    deleteButton: 'runtime-delete-button',
    editor: 'runtime-editor',
    meta: 'runtime-meta',
    metaLink: 'runtime-meta-link',
    commentBox: 'runtime-comment-box'
  },
  yaml: {
    filterRow: 'yaml-filter-row',
    filter: 'yaml-filter',
    active: 'is-active',
    check: 'yaml-check',
    checkOn: 'is-on',
    domainGrid: 'yaml-domain-grid',
    domainRule: 'yaml-domain-rule',
    ruleMeta: 'yaml-rule-meta',
    actions: 'yaml-actions',
    helper: 'yaml-helper',
    groupRow: 'yaml-group-row'
  },
  table: {
    centerCell: 'table-cell-center'
  },
  common: {
    emptyState: 'empty-state',
    outputBox: 'output-box',
    surfaceHelperText: 'surface-helper-text',
    mtBlock: 'u-mt-block'
  },
  settings: {
    interfaceThemeGrid: 'field-grid-2 interface-theme-grid',
    aiPlatformLinkRow: 'ai-platform-link-row',
    aiPlatformLink: 'ai-platform-link'
  },
  clipper: {
    shell: 'clipper-surface-window',
    body: 'clipper-surface-body',
    previewBlock: 'clipper-preview-block',
    preview: 'clipper-selection-preview',
    textarea: 'clipper-comment-textarea',
    sourceRow: 'clipper-source-row',
    sourceBadge: 'clipper-source-badge',
    sourceMeta: 'clipper-source-meta',
    sourceStatus: 'clipper-source-status',
    footerBar: 'clipper-footer-bar',
    footerSecondary: 'clipper-footer-secondary',
    footerPrimary: 'clipper-footer-primary'
  },
  session: {
    shellReader: 'reader-surface-window',
    shellVideo: 'video-surface-window',
    bodyReader: 'reader-surface-body',
    bodyVideo: 'video-surface-body',
    panelRail: 'session-panel-rail',
    resizeHandle: 'session-panel-resize-handle',
    heightResizeHandle: 'session-panel-height-resize-handle',
    list: 'session-item-list',
    item: 'session-item-card',
    readerItem: 'reader-session-item-card',
    addCaptureItem: 'session-add-capture-card',
    marker: 'session-item-marker',
    markerTime: 'session-item-marker-time',
    markerIndex: 'session-item-marker-index',
    addCaptureButton: 'session-add-capture-button',
    collapseTrigger: 'session-panel-collapse-trigger surface-window-header-action',
    content: 'session-item-content',
    readerContent: 'reader-session-item-content',
    readerSelection: 'reader-selection-text session-item-primary-line',
    readerNoteInput: 'reader-note-input',
    itemCloseTrigger: 'session-item-close-trigger',
    itemText: 'session-item-text',
    itemEditor: 'session-item-editor',
    commentInput: 'session-item-comment-input',
    metaRow: 'session-item-meta-row',
    footerCounter: 'session-counter',
    footerBar: 'session-footer-bar',
    footerActions: 'session-footer-actions',
    linkedSection: 'session-linked-section',
    linkedTitle: 'session-linked-title',
    linkedMeta: 'session-linked-meta',
    linkedAction: 'session-linked-action',
    linkedThumbPlay: 'surface-linked-thumb-play'
  }
} as const;

export type ClassNames = typeof classNames;
