import type { CompiledCatalog } from './compileCatalog';

const FILE_HEADER =
  '/* This file is generated by tools/generate-i18n-catalog.ts. Do not edit directly. */';

function renderKey(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function renderPackedArray(values: string[], indent = '  ', groupSize = 6): string[] {
  const lines: string[] = [];

  for (let index = 0; index < values.length; index += groupSize) {
    lines.push(
      `${indent}${values
        .slice(index, index + groupSize)
        .map((value) => renderKey(value))
        .join(', ')}${index + groupSize >= values.length ? '' : ','}`
    );
  }

  return lines;
}

export function emitGeneratedTypes(compiled: CompiledCatalog): string {
  return [
    FILE_HEADER,
    '',
    'export const GENERATED_MESSAGE_KEYS = [',
    ...renderPackedArray(compiled.messageKeys),
    '] as const;',
    '',
    'export type GeneratedMessageKey = (typeof GENERATED_MESSAGE_KEYS)[number];',
    '',
    'export type GeneratedMessages = Record<GeneratedMessageKey, string>;',
    ''
  ].join('\n');
}
