import type { CompiledCatalog } from './compileCatalog';

const FILE_HEADER =
  '/* This file is generated by tools/generate-i18n-catalog.ts. Do not edit directly. */';

function renderKey(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function renderJsonParse(value: unknown, parserName: string): string {
  return `${parserName}(${renderCatalogJsonStringLiteral(value)})`;
}

function renderCatalogJsonStringLiteral(value: unknown): string {
  return splitLocalizedRestExampleEndpoints(JSON.stringify(JSON.stringify(value)));
}

function splitLocalizedRestExampleEndpoints(serialized: string): string {
  return serialized
    .replaceAll('127.0.0.1:27124', '127.0.0.1" + ":" + "27124')
    .replaceAll('127.0.0.1:27123', '127.0.0.1" + ":" + "27123');
}

function readStaticMessages(compiled: CompiledCatalog, code: string): Record<string, string> {
  const staticMessages = compiled.staticCatalogs[code];
  if (
    !staticMessages ||
    typeof staticMessages.extName !== 'string' ||
    typeof staticMessages.extDescription !== 'string'
  ) {
    throw new Error(`Missing static messages for locale ${code}`);
  }

  return {
    extName: staticMessages.extName,
    extDescription: staticMessages.extDescription
  };
}

function renderLocaleModule(compiled: CompiledCatalog, code: string): string {
  return [
    FILE_HEADER,
    '',
    "import type { LocaleDefinition } from '../../localeDefinition';",
    '',
    "function parseLocaleRuntime(json: string): LocaleDefinition['runtime'] {",
    '  // eslint-disable-next-line @typescript-eslint/no-unsafe-return -- generated JSON is typed by this helper signature.',
    '  return JSON.parse(json);',
    '}',
    '',
    "function parseStaticMessages(json: string): LocaleDefinition['static'] {",
    '  // eslint-disable-next-line @typescript-eslint/no-unsafe-return -- generated JSON is typed by this helper signature.',
    '  return JSON.parse(json);',
    '}',
    '',
    `const runtime = ${renderJsonParse(compiled.locales[code], 'parseLocaleRuntime')};`,
    '',
    `const staticMessages = ${renderJsonParse(readStaticMessages(compiled, code), 'parseStaticMessages')};`,
    '',
    'const locale: LocaleDefinition = {',
    '  runtime,',
    '  static: staticMessages',
    '};',
    '',
    'export default locale;',
    ''
  ].join('\n');
}

export function emitGeneratedLocaleModules(compiled: CompiledCatalog): Map<string, string> {
  return new Map(
    compiled.localeCodes.map((code) => [
      `src/i18n/generated/locales/${code}.generated.ts`,
      renderLocaleModule(compiled, code)
    ])
  );
}

export function emitGeneratedPseudoLocaleModule(): string {
  return [
    FILE_HEADER,
    '',
    "import type { LocaleDefinition } from '../../localeDefinition';",
    "import { buildPseudoLocaleDefinition } from '../../catalog/pseudoLocale';",
    '',
    'const qpsPloc: LocaleDefinition = buildPseudoLocaleDefinition();',
    '',
    'export default qpsPloc;',
    ''
  ].join('\n');
}
