import type { CompiledCatalog } from './compileCatalog';

const FILE_HEADER =
  '/* This file is generated by tools/generate-i18n-catalog.ts. Do not edit directly. */';

function renderKey(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

export function emitGeneratedTypes(compiled: CompiledCatalog): string {
  const keyLines = compiled.messageKeys.map((key) => `  ${renderKey(key)},`);
  const interfaceLines = compiled.messageKeys.map((key) => `  ${renderKey(key)}: string;`);

  return [
    FILE_HEADER,
    '',
    'export const GENERATED_MESSAGE_KEYS = [',
    ...keyLines,
    '] as const;',
    '',
    'export type GeneratedMessageKey = (typeof GENERATED_MESSAGE_KEYS)[number];',
    '',
    'export interface GeneratedMessages {',
    ...interfaceLines,
    '}',
    ''
  ].join('\n');
}
