import type { CompiledCatalog } from './compileCatalog';

const FILE_HEADER =
  '/* This file is generated by tools/generate-i18n-catalog.ts. Do not edit directly. */';

const SCHEMA_EXPORT_ALIASES = {
  en: ['schemaShellMessagesEn', 'schemaShellMessagesEnglish'],
  'zh-CN': ['schemaShellMessagesZhHans'],
  ja: ['schemaShellMessagesJa'],
  de: ['schemaShellMessagesDe'],
  fr: ['schemaShellMessagesFr'],
  'es-ES': ['schemaShellMessagesEsEs'],
  'es-419': ['schemaShellMessagesEs419'],
  it: ['schemaShellMessagesIt'],
  ko: ['schemaShellMessagesKo'],
  'pt-BR': ['schemaShellMessagesPtBr'],
  ru: ['schemaShellMessagesRu'],
  'zh-TW': ['schemaShellMessagesZhHant']
} as const;

function renderKey(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function renderSchemaConstantName(code: string): string {
  return `GENERATED_RELEASE_SCHEMA_MESSAGES_${code
    .replace(/[^A-Za-z0-9]+/g, '_')
    .toUpperCase()}`;
}

function renderLocaleMessages(messages: Record<string, string>): string[] {
  return [
    '{',
    ...Object.entries(messages).map(
      ([key, value]) => `    ${renderKey(key)}: ${JSON.stringify(value)},`
    ),
    '  }'
  ];
}

export function emitGeneratedSchemaMessages(compiled: CompiledCatalog): string {
  const schemaKeyLines = compiled.messageKeys.map((key) => `  ${renderKey(key)},`);
  const localeCodeLines = compiled.localeCodes.map((code) => `  ${renderKey(code)},`);
  const localeConstantLines = compiled.localeCodes.flatMap((code) => {
    const locale = compiled.locales[code];
    return [
      `export const ${renderSchemaConstantName(code)}: GeneratedSchemaMessages = ${renderLocaleMessages(
        locale
      ).join('\n')};`,
      ''
    ];
  });
  const registryLines = compiled.localeCodes.flatMap((code) => {
    return [`  ${renderKey(code)}: ${renderSchemaConstantName(code)},`];
  });
  const aliasLines = compiled.localeCodes.flatMap((code) => {
    const aliases = SCHEMA_EXPORT_ALIASES[code as keyof typeof SCHEMA_EXPORT_ALIASES] ?? [];
    return aliases.map(
      (alias) => `export const ${alias} = ${renderSchemaConstantName(code)};`
    );
  });

  return [
    FILE_HEADER,
    '',
    "import type { ReleaseLangCode } from '../catalog/languages';",
    "import type { SchemaMessageKey } from '../catalog/schemaKeys';",
    '',
    'export type GeneratedSchemaMessages = Record<SchemaMessageKey, string>;',
    '',
    'export const GENERATED_SCHEMA_MESSAGE_KEYS = [',
    ...schemaKeyLines,
    '] as const satisfies readonly SchemaMessageKey[];',
    '',
    'export const GENERATED_RELEASE_SCHEMA_MESSAGE_CODES = [',
    ...localeCodeLines,
    '] as const satisfies readonly ReleaseLangCode[];',
    '',
    ...localeConstantLines,
    'export const GENERATED_RELEASE_SCHEMA_MESSAGES: Record<ReleaseLangCode, GeneratedSchemaMessages> = {',
    ...registryLines,
    '};',
    '',
    ...aliasLines,
    ''
  ].join('\n');
}
