import type { CompiledCatalog } from './compileCatalog';

const FILE_HEADER =
  '/* This file is generated by tools/generate-i18n-catalog.ts. Do not edit directly. */';

function renderKey(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function renderLocaleMessages(messages: Record<string, string>): string[] {
  return [
    '{',
    ...Object.entries(messages).map(
      ([key, value]) => `    ${renderKey(key)}: ${JSON.stringify(value)},`
    ),
    '  }'
  ];
}

export function emitGeneratedLocales(compiled: CompiledCatalog): string {
  const localeCodeLines = compiled.localeCodes.map((code) => `  ${renderKey(code)},`);
  const registryLines = compiled.localeCodes.flatMap((code) => {
    const locale = compiled.locales[code];
    return [`  ${renderKey(code)}: ${renderLocaleMessages(locale).join('\n')},`];
  });

  return [
    FILE_HEADER,
    '',
    "import type { ReleaseLangCode } from '../catalog/languages';",
    "import type { GeneratedMessages } from './messages.generated';",
    '',
    'export type GeneratedLocaleRegistry = Record<ReleaseLangCode, GeneratedMessages>;',
    '',
    'export const GENERATED_RELEASE_LOCALE_CODES = [',
    ...localeCodeLines,
    '] as const satisfies readonly ReleaseLangCode[];',
    '',
    'export const GENERATED_RELEASE_LOCALE_REGISTRY: GeneratedLocaleRegistry = {',
    ...registryLines,
    '};',
    ''
  ].join('\n');
}
