import type { CompiledCatalog } from './compileCatalog';

const FILE_HEADER =
  '/* This file is generated by tools/generate-i18n-catalog.ts. Do not edit directly. */';

function renderKey(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function renderLocaleConstantName(code: string): string {
  return `GENERATED_RELEASE_LOCALE_MESSAGES_${code
    .replace(/[^A-Za-z0-9]+/g, '_')
    .toUpperCase()}`;
}

function renderPackedArray(values: string[], indent = '  ', groupSize = 6): string[] {
  const lines: string[] = [];

  for (let index = 0; index < values.length; index += groupSize) {
    lines.push(
      `${indent}${values
        .slice(index, index + groupSize)
        .map((value) => renderKey(value))
        .join(', ')}${index + groupSize >= values.length ? '' : ','}`
    );
  }

  return lines;
}

function renderJsonParse(value: unknown, typeName: string): string {
  return `JSON.parse(${JSON.stringify(JSON.stringify(value))}) as ${typeName}`;
}

export function emitGeneratedLocales(compiled: CompiledCatalog): string {
  const localeConstantLines = compiled.localeCodes.flatMap((code) => {
    const locale = compiled.locales[code];
    return [
      `export const ${renderLocaleConstantName(code)} = ${renderJsonParse(locale, 'GeneratedMessages')};`,
      ''
    ];
  });
  const registryLines = compiled.localeCodes.flatMap((code) => {
    return [`  ${renderKey(code)}: ${renderLocaleConstantName(code)},`];
  });

  return [
    FILE_HEADER,
    '',
    "import type { ReleaseLangCode } from '../catalog/languages';",
    "import type { GeneratedMessages } from './messages.generated';",
    '',
    'export type GeneratedLocaleRegistry = Record<ReleaseLangCode, GeneratedMessages>;',
    '',
    'export const GENERATED_RELEASE_LOCALE_CODES = [',
    ...renderPackedArray(compiled.localeCodes),
    '] as const satisfies readonly ReleaseLangCode[];',
    '',
    ...localeConstantLines,
    'export const GENERATED_RELEASE_LOCALE_REGISTRY: GeneratedLocaleRegistry = {',
    ...registryLines,
    '};',
    ''
  ].join('\n');
}
