import type { CompiledCatalog } from './compileCatalog';

const FILE_HEADER =
  '/* This file is generated by tools/generate-i18n-catalog.ts. Do not edit directly. */';

function renderKey(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function renderStaticConstantName(code: string): string {
  return `GENERATED_RELEASE_STATIC_MESSAGES_${code
    .replace(/[^A-Za-z0-9]+/g, '_')
    .toUpperCase()}`;
}

function readStaticMessages(compiled: CompiledCatalog, code: string): Record<string, string> {
  const staticMessages = compiled.staticCatalogs[code];
  if (
    !staticMessages ||
    typeof staticMessages.extName !== 'string' ||
    typeof staticMessages.extDescription !== 'string'
  ) {
    throw new Error(`Missing static messages for locale ${code}`);
  }

  return {
    extName: staticMessages.extName,
    extDescription: staticMessages.extDescription
  };
}

function renderRecord(messages: Record<string, string>): string[] {
  return [
    '{',
    ...Object.entries(messages).map(
      ([key, value]) => `  ${renderKey(key)}: ${JSON.stringify(value)},`
    ),
    '}'
  ];
}

export function emitGeneratedStaticRegistry(compiled: CompiledCatalog): string {
  const staticConstantLines = compiled.localeCodes.flatMap((code) => [
    `export const ${renderStaticConstantName(code)}: LocaleStaticMessages = ${renderRecord(
      readStaticMessages(compiled, code)
    ).join('\n')};`,
    ''
  ]);
  const registryLines = compiled.localeCodes.map(
    (code) => `  ${renderKey(code)}: ${renderStaticConstantName(code)},`
  );

  return [
    FILE_HEADER,
    '',
    "import type { ReleaseLangCode } from '../catalog/languages';",
    "import type { LocaleStaticMessages } from '../localeDefinition';",
    '',
    'export type GeneratedStaticRegistry = Record<ReleaseLangCode, LocaleStaticMessages>;',
    '',
    ...staticConstantLines,
    'export const GENERATED_RELEASE_STATIC_REGISTRY: GeneratedStaticRegistry = {',
    ...registryLines,
    '};',
    ''
  ].join('\n');
}
