import type { CompiledCatalog } from './compileCatalog';

const FILE_HEADER =
  '/* This file is generated by tools/generate-i18n-catalog.ts. Do not edit directly. */';

const SCHEMA_EXPORT_ALIASES = {
  en: ['schemaShellMessagesEn', 'schemaShellMessagesEnglish'],
  'zh-CN': ['schemaShellMessagesZhHans'],
  ja: ['schemaShellMessagesJa'],
  de: ['schemaShellMessagesDe'],
  fr: ['schemaShellMessagesFr'],
  'es-ES': ['schemaShellMessagesEsEs'],
  'es-419': ['schemaShellMessagesEs419'],
  it: ['schemaShellMessagesIt'],
  ko: ['schemaShellMessagesKo'],
  'pt-BR': ['schemaShellMessagesPtBr'],
  ru: ['schemaShellMessagesRu'],
  'zh-TW': ['schemaShellMessagesZhHant']
} as const;

function renderKey(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function renderSchemaConstantName(code: string): string {
  return `GENERATED_RELEASE_SCHEMA_MESSAGES_${code
    .replace(/[^A-Za-z0-9]+/g, '_')
    .toUpperCase()}`;
}

function renderPackedArray(values: string[], indent = '  ', groupSize = 6): string[] {
  const lines: string[] = [];

  for (let index = 0; index < values.length; index += groupSize) {
    lines.push(
      `${indent}${values
        .slice(index, index + groupSize)
        .map((value) => renderKey(value))
        .join(', ')}${index + groupSize >= values.length ? '' : ','}`
    );
  }

  return lines;
}

function renderCatalogJsonStringLiteral(value: unknown): string {
  return splitLocalizedRestExampleEndpoints(JSON.stringify(JSON.stringify(value)));
}

function splitLocalizedRestExampleEndpoints(serialized: string): string {
  return serialized
    .replaceAll('127.0.0.1:27124', '127.0.0.1" + ":" + "27124')
    .replaceAll('127.0.0.1:27123', '127.0.0.1" + ":" + "27123');
}

export function emitGeneratedSchemaMessages(compiled: CompiledCatalog): string {
  const localeConstantLines = compiled.localeCodes.flatMap((code) => {
    const locale = compiled.locales[code];
    const values = compiled.messageKeys.map((key) => locale[key] ?? '');

    return [
      `const ${renderSchemaConstantName(code)}_VALUES = parseSchemaMessageValues(${renderCatalogJsonStringLiteral(
        values
      )});`,
      '',
      `export const ${renderSchemaConstantName(code)} = buildSchemaMessages(${renderSchemaConstantName(
        code
      )}_VALUES);`,
      ''
    ];
  });
  const registryLines = compiled.localeCodes.flatMap((code) => {
    return [`  ${renderKey(code)}: ${renderSchemaConstantName(code)},`];
  });
  const aliasLines = compiled.localeCodes.flatMap((code) => {
    const aliases = SCHEMA_EXPORT_ALIASES[code as keyof typeof SCHEMA_EXPORT_ALIASES] ?? [];
    return aliases.map(
      (alias) => `export const ${alias} = ${renderSchemaConstantName(code)};`
    );
  });

  return [
    FILE_HEADER,
    '',
    "import type { ReleaseLangCode } from '../catalog/languages';",
    '',
    'export type GeneratedSchemaMessageKey = (typeof GENERATED_SCHEMA_MESSAGE_KEYS)[number];',
    '',
    'export type GeneratedSchemaMessages = Record<GeneratedSchemaMessageKey, string>;',
    '',
    'function buildSchemaMessages(values: readonly string[]): GeneratedSchemaMessages {',
    '  return Object.fromEntries(',
    '    GENERATED_SCHEMA_MESSAGE_KEYS.map((key, index) => [key, values[index] ?? \'\'])',
    '  ) as GeneratedSchemaMessages;',
    '}',
    '',
    'export const GENERATED_SCHEMA_MESSAGE_KEYS = [',
    ...renderPackedArray(compiled.messageKeys),
    '] as const;',
    '',
    'function parseSchemaMessageValues(json: string): readonly string[] {',
    '  return JSON.parse(json) as readonly string[];',
    '}',
    '',
    ...localeConstantLines,
    'export const GENERATED_RELEASE_SCHEMA_MESSAGES: Record<ReleaseLangCode, GeneratedSchemaMessages> = {',
    ...registryLines,
    '};',
    '',
    ...aliasLines,
    ''
  ].join('\n');
}
