import type { CompiledCatalog } from './compileCatalog';

const FILE_HEADER =
  '/* This file is generated by tools/generate-i18n-catalog.ts. Do not edit directly. */';

const SCHEMA_EXPORT_ALIASES = {
  en: ['schemaShellMessagesEn', 'schemaShellMessagesEnglish'],
  'zh-CN': ['schemaShellMessagesZhHans'],
  ja: ['schemaShellMessagesJa'],
  de: ['schemaShellMessagesDe'],
  fr: ['schemaShellMessagesFr'],
  'es-ES': ['schemaShellMessagesEsEs'],
  'es-419': ['schemaShellMessagesEs419'],
  it: ['schemaShellMessagesIt'],
  ko: ['schemaShellMessagesKo'],
  'pt-BR': ['schemaShellMessagesPtBr'],
  ru: ['schemaShellMessagesRu'],
  'zh-TW': ['schemaShellMessagesZhHant']
} as const;

function renderKey(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function renderSchemaConstantName(code: string): string {
  return `GENERATED_RELEASE_SCHEMA_MESSAGES_${code
    .replace(/[^A-Za-z0-9]+/g, '_')
    .toUpperCase()}`;
}

function renderSchemaModulePath(code: string): string {
  return `./schema/${code}.generated`;
}

function renderPackedArray(values: string[], indent = '  ', groupSize = 6): string[] {
  const lines: string[] = [];

  for (let index = 0; index < values.length; index += groupSize) {
    lines.push(
      `${indent}${values
        .slice(index, index + groupSize)
        .map((value) => renderKey(value))
        .join(', ')}${index + groupSize >= values.length ? '' : ','}`
    );
  }

  return lines;
}

function renderCatalogJsonStringLiteral(value: unknown): string {
  return splitLocalizedRestExampleEndpoints(JSON.stringify(JSON.stringify(value)));
}

function splitLocalizedRestExampleEndpoints(serialized: string): string {
  return serialized
    .replaceAll('127.0.0.1:27124', '127.0.0.1" + ":" + "27124')
    .replaceAll('127.0.0.1:27123', '127.0.0.1" + ":" + "27123');
}

export function emitGeneratedSchemaCore(compiled: CompiledCatalog): string {
  return [
    FILE_HEADER,
    '',
    'export type GeneratedSchemaMessageKey = (typeof GENERATED_SCHEMA_MESSAGE_KEYS)[number];',
    '',
    'export type GeneratedSchemaMessages = Record<GeneratedSchemaMessageKey, string>;',
    '',
    'export function buildSchemaMessages(values: readonly string[]): GeneratedSchemaMessages {',
    '  return Object.fromEntries(',
    '    GENERATED_SCHEMA_MESSAGE_KEYS.map((key, index) => [key, values[index] ?? \'\'])',
    '  ) as GeneratedSchemaMessages;',
    '}',
    '',
    'export const GENERATED_SCHEMA_MESSAGE_KEYS = [',
    ...renderPackedArray(compiled.messageKeys),
    '] as const;',
    '',
    'export function parseSchemaMessageValues(json: string): readonly string[] {',
    '  return JSON.parse(json) as readonly string[];',
    '}',
    ''
  ].join('\n');
}

export function emitGeneratedSchemaLocaleModules(compiled: CompiledCatalog): Array<{
  path: string;
  content: string;
}> {
  return compiled.localeCodes.map((code) => {
    const locale = compiled.locales[code];
    const values = compiled.messageKeys.map((key) => locale[key] ?? '');
    const constantName = renderSchemaConstantName(code);

    return {
      path: `src/i18n/generated/schema/${code}.generated.ts`,
      content: [
        FILE_HEADER,
        '',
        "import { buildSchemaMessages, parseSchemaMessageValues } from '../schemaCore.generated';",
        '',
        `const ${constantName}_VALUES = parseSchemaMessageValues(${renderCatalogJsonStringLiteral(
          values
        )});`,
        '',
        `export const ${constantName} = buildSchemaMessages(${constantName}_VALUES);`,
        ''
      ].join('\n')
    };
  });
}

export function emitGeneratedSchemaMessages(compiled: CompiledCatalog): string {
  const importLines = compiled.localeCodes.map((code) => {
    return `import { ${renderSchemaConstantName(code)} } from '${renderSchemaModulePath(code)}';`;
  });
  const registryLines = compiled.localeCodes.flatMap((code) => {
    return [`  ${renderKey(code)}: ${renderSchemaConstantName(code)},`];
  });
  const aliasLines = compiled.localeCodes.flatMap((code) => {
    const aliases = SCHEMA_EXPORT_ALIASES[code as keyof typeof SCHEMA_EXPORT_ALIASES] ?? [];
    return aliases.map(
      (alias) => `export const ${alias} = ${renderSchemaConstantName(code)};`
    );
  });

  return [
    FILE_HEADER,
    '',
    "import type { ReleaseLangCode } from '../catalog/languages';",
    "import type { GeneratedSchemaMessages } from './schemaCore.generated';",
    ...importLines,
    '',
    "export type { GeneratedSchemaMessageKey, GeneratedSchemaMessages } from './schemaCore.generated';",
    "export { GENERATED_SCHEMA_MESSAGE_KEYS } from './schemaCore.generated';",
    '',
    'export const GENERATED_RELEASE_SCHEMA_MESSAGES: Record<ReleaseLangCode, GeneratedSchemaMessages> = {',
    ...registryLines,
    '};',
    '',
    ...aliasLines,
    ''
  ].join('\n');
}
