import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import prettier from 'prettier';
import type { CompiledCatalog } from './compileCatalog';
import { emitGeneratedChromeLocales } from './emitGeneratedChromeLocales';
import {
  emitGeneratedLocaleModules,
  emitGeneratedPseudoLocaleModule
} from './emitGeneratedLocaleModules';
import { emitGeneratedLocales } from './emitGeneratedLocales';
import { emitGeneratedStaticRegistry } from './emitGeneratedStaticRegistry';
import { emitGeneratedTypes } from './emitGeneratedTypes';

export interface GeneratedArtifactDrift {
  path: string;
  reason: 'missing' | 'content-mismatch';
}

export interface GeneratedArtifactCatalogs {
  runtime: CompiledCatalog;
  schema?: CompiledCatalog;
}

const FILE_HEADER =
  '/* This file is generated by tools/generate-i18n-catalog.ts. Do not edit directly. */';

function renderKey(value: string): string {
  return JSON.stringify(value);
}

function renderPackedStringArray(values: string[], indent = '  ', groupSize = 4): string[] {
  const lines: string[] = [];

  for (let index = 0; index < values.length; index += groupSize) {
    lines.push(
      `${indent}${values
        .slice(index, index + groupSize)
        .map((value) => renderKey(value))
        .join(', ')}${index + groupSize >= values.length ? '' : ','}`
    );
  }

  return lines;
}

function renderSchemaLocaleConstantName(code: string): string {
  return `GENERATED_RELEASE_SCHEMA_MESSAGES_${code
    .replace(/[^A-Za-z0-9]+/g, '_')
    .toUpperCase()}`;
}

function renderCatalogJsonStringLiteral(value: unknown): string {
  return JSON.stringify(JSON.stringify(value));
}

function emitCompressedSchemaMessages(compiled: CompiledCatalog): string {
  const keys = compiled.messageKeys;
  const localeValueLines = compiled.localeCodes.flatMap((code) => {
    const locale = compiled.locales[code];
    const values = keys.map((key) => locale[key] ?? '');

    return [
      `const ${renderSchemaLocaleConstantName(code)}_VALUES = parseSchemaMessageValues(${renderCatalogJsonStringLiteral(
        values
      )});`,
      '',
      `export const ${renderSchemaLocaleConstantName(code)} = buildSchemaMessages(${renderSchemaLocaleConstantName(
        code
      )}_VALUES);`,
      ''
    ];
  });

  const registryLines = compiled.localeCodes.map(
    (code) => `  ${renderKey(code)}: ${renderSchemaLocaleConstantName(code)},`
  );

  return [
    FILE_HEADER,
    '',
    "import type { ReleaseLangCode } from '../catalog/languages';",
    '',
    'export const GENERATED_SCHEMA_MESSAGE_KEYS = [',
    ...renderPackedStringArray(keys, '  ', 6),
    '] as const;',
    '',
    'export type GeneratedSchemaMessageKey = (typeof GENERATED_SCHEMA_MESSAGE_KEYS)[number];',
    '',
    'export type GeneratedSchemaMessages = Record<GeneratedSchemaMessageKey, string>;',
    '',
    'function buildSchemaMessages(values: readonly string[]): GeneratedSchemaMessages {',
    '  return Object.fromEntries(',
    '    GENERATED_SCHEMA_MESSAGE_KEYS.map((key, index) => [key, values[index] ?? \'\'])',
    '  ) as GeneratedSchemaMessages;',
    '}',
    '',
    'function parseSchemaMessageValues(json: string): readonly string[] {',
    '  return JSON.parse(json) as readonly string[];',
    '}',
    '',
    ...localeValueLines,
    'export const GENERATED_RELEASE_SCHEMA_MESSAGES: Record<ReleaseLangCode, GeneratedSchemaMessages> = {',
    ...registryLines,
    '};',
    '',
    'export const schemaShellMessagesEn = GENERATED_RELEASE_SCHEMA_MESSAGES_EN;',
    'export const schemaShellMessagesEnglish = GENERATED_RELEASE_SCHEMA_MESSAGES_EN;',
    'export const schemaShellMessagesZhHans = GENERATED_RELEASE_SCHEMA_MESSAGES_ZH_CN;',
    'export const schemaShellMessagesJa = GENERATED_RELEASE_SCHEMA_MESSAGES_JA;',
    'export const schemaShellMessagesDe = GENERATED_RELEASE_SCHEMA_MESSAGES_DE;',
    'export const schemaShellMessagesFr = GENERATED_RELEASE_SCHEMA_MESSAGES_FR;',
    'export const schemaShellMessagesEsEs = GENERATED_RELEASE_SCHEMA_MESSAGES_ES_ES;',
    'export const schemaShellMessagesEs419 = GENERATED_RELEASE_SCHEMA_MESSAGES_ES_419;',
    'export const schemaShellMessagesIt = GENERATED_RELEASE_SCHEMA_MESSAGES_IT;',
    'export const schemaShellMessagesKo = GENERATED_RELEASE_SCHEMA_MESSAGES_KO;',
    'export const schemaShellMessagesPtBr = GENERATED_RELEASE_SCHEMA_MESSAGES_PT_BR;',
    'export const schemaShellMessagesRu = GENERATED_RELEASE_SCHEMA_MESSAGES_RU;',
    'export const schemaShellMessagesZhHant = GENERATED_RELEASE_SCHEMA_MESSAGES_ZH_TW;',
    ''
  ].join('\n');
}

async function formatGeneratedArtifact(
  rootDir: string,
  relativePath: string,
  content: string
): Promise<string> {
  const filePath = path.join(rootDir, relativePath);
  const prettierOptions = await prettier.resolveConfig(filePath);

  return prettier.format(content, {
    ...(prettierOptions ?? {}),
    filepath: filePath
  });
}

export async function buildGeneratedArtifacts(
  compiledOrCatalogs: CompiledCatalog | GeneratedArtifactCatalogs,
  rootDir = process.cwd()
): Promise<Map<string, string>> {
  const { runtime, schema } =
    'runtime' in compiledOrCatalogs ? compiledOrCatalogs : { runtime: compiledOrCatalogs };
  const rawArtifacts = new Map<string, string>([
    ['src/i18n/generated/messages.generated.ts', emitGeneratedTypes(runtime)],
    ['src/i18n/generated/localeRegistry.generated.ts', emitGeneratedLocales(runtime)],
    ['src/i18n/generated/staticRegistry.generated.ts', emitGeneratedStaticRegistry(runtime)],
    ...emitGeneratedLocaleModules(runtime),
    [
      'src/i18n/generated/locales/qps-ploc.generated.ts',
      emitGeneratedPseudoLocaleModule()
    ],
    ...emitGeneratedChromeLocales(runtime)
  ]);

  if (schema) {
    rawArtifacts.set(
      'src/i18n/generated/schemaMessages.generated.ts',
      emitCompressedSchemaMessages(schema)
    );
  }

  const formattedEntries = await Promise.all(
    [...rawArtifacts.entries()].map(
      async ([relativePath, content]) =>
        [relativePath, await formatGeneratedArtifact(rootDir, relativePath, content)] as const
    )
  );

  return new Map<string, string>(formattedEntries);
}

export function diffGeneratedArtifacts(
  rootDir: string,
  artifacts: Map<string, string>
): GeneratedArtifactDrift[] {
  const drift: GeneratedArtifactDrift[] = [];

  for (const [relativePath, expectedContent] of artifacts) {
    const filePath = path.join(rootDir, relativePath);
    if (!existsSync(filePath)) {
      drift.push({ path: relativePath, reason: 'missing' });
      continue;
    }

    const currentContent = readFileSync(filePath, 'utf8');
    if (currentContent !== expectedContent) {
      drift.push({ path: relativePath, reason: 'content-mismatch' });
    }
  }

  return drift;
}

export function writeGeneratedArtifacts(rootDir: string, artifacts: Map<string, string>): string[] {
  const changedPaths: string[] = [];

  for (const [relativePath, content] of artifacts) {
    const filePath = path.join(rootDir, relativePath);
    const currentContent = existsSync(filePath) ? readFileSync(filePath, 'utf8') : null;

    if (currentContent === content) {
      continue;
    }

    mkdirSync(path.dirname(filePath), { recursive: true });
    writeFileSync(filePath, content, 'utf8');
    changedPaths.push(relativePath);
  }

  return changedPaths;
}
