import path from 'node:path';
import { fileURLToPath } from 'node:url';
import fs from 'node:fs/promises';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT = path.resolve(__dirname, '..');
const OUTPUT_FILE = path.join(ROOT, 'src/i18n/locales/qps-ploc.ts');

function generateContent(): string {
  return `/* This file is generated by tools/generate-pseudo-locale.ts. Do not edit directly. */

import type { LocaleDefinition } from '../localeDefinition';
import { buildPseudoLocaleDefinition } from '../catalog/pseudoLocale';

const qpsPloc: LocaleDefinition = buildPseudoLocaleDefinition();

export default qpsPloc;
`;
}

async function main(): Promise<void> {
  const content = generateContent();
  await fs.writeFile(OUTPUT_FILE, content, 'utf8');
  console.log(`✅ Pseudo locale regenerated at ${path.relative(ROOT, OUTPUT_FILE)}`);
}

main().catch((error) => {
  console.error('Failed to generate pseudo locale');
  console.error(error);
  process.exitCode = 1;
});
