/* This file is generated by tools/generate-pseudo-locale.ts. Do not edit directly. */

import type { LocaleDefinition } from '../localeDefinition';
import { buildPseudoLocaleDefinition } from '../catalog/pseudoLocale';

const qpsPloc: LocaleDefinition = buildPseudoLocaleDefinition();

export default qpsPloc;
